//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DosProtectedResources) DeepCopyInto(out *DosProtectedResources) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DosProtectedResources.
func (in *DosProtectedResources) DeepCopy() *DosProtectedResources {
	if in == nil {
		return nil
	}
	out := new(DosProtectedResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DosProtectedResources) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DosProtectedResourceList) DeepCopyInto(out *DosProtectedResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DosProtectedResources, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DosProtectedResourceList.
func (in *DosProtectedResourceList) DeepCopy() *DosProtectedResourceList {
	if in == nil {
		return nil
	}
	out := new(DosProtectedResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DosProtectedResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DosProtectedResourcesSpec) DeepCopyInto(out *DosProtectedResourcesSpec) {
	*out = *in
	if in.DosSecurityLog != nil {
		in, out := &in.DosSecurityLog, &out.DosSecurityLog
		*out = new(DosSecurityLog)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DosProtectedResourcesSpec.
func (in *DosProtectedResourcesSpec) DeepCopy() *DosProtectedResourcesSpec {
	if in == nil {
		return nil
	}
	out := new(DosProtectedResourcesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DosSecurityLog) DeepCopyInto(out *DosSecurityLog) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DosSecurityLog.
func (in *DosSecurityLog) DeepCopy() *DosSecurityLog {
	if in == nil {
		return nil
	}
	out := new(DosSecurityLog)
	in.DeepCopyInto(out)
	return out
}
